name: dependency_injection_dio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: ^8.1.0
  injectable_generator: ^2.5.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
